import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Navbar from "@/components/navbar/navbar";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Edson Brandon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={poppins.className}>
      <body className="px-20 py-10">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
